version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies needed for HTML project"

  build:
    commands:
      - echo "Build phase - nothing to compile for static HTML"

  post_build:
    commands:
      - echo "Zipping files for deployment"
      - zip -r website.zip .

artifacts:
  files:
    - '**/*'
  name: website.zip
  discard-paths: no
