version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies needed for HTML project"

  build:
    commands:
      - echo "Build phase - nothing to compile for static HTML"

  post_build:
    commands:
      - echo "Copying files to S3 bucket"
      - aws s3 cp index.html s3://liukang2025/
      - aws s3 cp error.html s3://liukang2025/
      - aws s3 cp --recursive . s3://liukang2025/

artifacts:
  files:
    - 'index.html'
    - 'error.html'
    - '**/*'
  discard-paths: no
